### ISSUE TITLE
Crash on onRestoreInstanceState

### ISSUE THREAD

**Issue by gnuhel** [vikramkakkar/SublimeNavigationView#17]
@vikramkakkar Hi, if you release the newest version, could you please look into this crash.
It crashes after returning to the app when it was closed for a long time.

Thanks

`
07-29 09:27:36.397 19264-19264/? E/Parcel: Class not found when unmarshalling: com.appeaser.sublimenavigationviewlibrary.SublimeMenu
                                           java.lang.ClassNotFoundException: com.appeaser.sublimenavigationviewlibrary.SublimeMenu
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.Class.forName(Class.java:324)
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                               at android.os.Parcel.readParcelable(Parcel.java:2358)
                                               at android.os.Parcel.readValue(Parcel.java:2264)
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                               at android.os.BaseBundle.containsKey(BaseBundle.java:269)
                                               at com.appeaser.sublimenavigationviewlibrary.SublimeNavigationView.onRestoreInstanceState(SublimeNavigationView.java:479)
                                               at android.view.View.dispatchRestoreInstanceState(View.java:14752)
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                               at android.view.View.restoreHierarchyState(View.java:14730)
                                               at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
                                               at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
                                               at android.app.Activity.performRestoreInstanceState(Activity.java:963)
                                               at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:148)
                                               at android.app.ActivityThread.main(ActivityThread.java:5422)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                            Caused by: java.lang.ClassNotFoundException: com.appeaser.sublimenavigationviewlibrary.SublimeMenu
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:324) 
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                               at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                               at android.os.Parcel.readValue(Parcel.java:2264) 
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                               at android.os.BaseBundle.containsKey(BaseBundle.java:269) 
                                               at com.appeaser.sublimenavigationviewlibrary.SublimeNavigationView.onRestoreInstanceState(SublimeNavigationView.java:479) 
                                               at android.view.View.dispatchRestoreInstanceState(View.java:14752) 
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121) 
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127) 
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127) 
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127) 
                                               at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127) 
                                               at android.view.View.restoreHierarchyState(View.java:14730) 
                                               at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035) 
                                               at android.app.Activity.onRestoreInstanceState(Activity.java:1008) 
                                               at android.app.Activity.performRestoreInstanceState(Activity.java:963) 
                                               at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163) 
                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389) 
                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                               at android.os.Looper.loop(Looper.java:148) 
                                               at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                               at java.lang.reflect.Method.invoke(Native Method) 
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
`

**Comment by alashow** [comment]
The bug has a fix on dev branch. See #7 for another report and [this](https://github.com/vikramkakkar/SublimeNavigationView/issues/2#issuecomment-186410937) for how to use dev branch/fixes.

@vikramkakkar needs to merge dev branch to master tho :) Otherwise issues are being re-opened repeatedly.
